name: whereismykid
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  getwidget: ^4.0.0
  google_maps_flutter: ^2.3.0
  loading_animation_widget: ^1.2.0+4
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  google_sign_in: ^5.2.0
  

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1
  signalr_netcore: ^1.3.7
  permission_handler: ^11.3.0
  background_fetch: ^1.2.3
  background_location: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/google-maps-pin.png
    - assets/images/
